#
# GET http://localhost:3001/

#
POST http://localhost:3001/notes HTTP/1.1
content-type: application/json

{
    "content": null,
    "important": true
}

#
POST http://localhost:3001/notes HTTP/1.1
content-type: application/json

{
    "content": "laving this",
    "important": true
}