#
POST http://localhost:3001/api/persons/
Content-type: application/json

{
    "name": "test2",
    "number": 123
}


PUT http://localhost:3001/api/persons/2
Content-type: application/json

{
    "name": "t",
    "number": 123
}

##
GET http://localhost:3001/api/persons/2
